In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import dsbmm_bp.simulation as dsbmm_sim


In [34]:
Q = 4
T = 5
N = 100
Z_1 = np.random.randint(0, Q, size=(N,))
meta_types = ["poisson", "indep bernoulli"]
L = 5
meta_params = [np.random.randint(5, 15, size=(1, Q, T)), np.random.rand(L, Q, T)]

dsbmm_dict = dsbmm_sim.sample_dynsbm_meta(
    Z_1=Z_1, Q=Q, T=T, meta_types=meta_types, meta_dims=[1, L], meta_params=meta_params
)



In [42]:
# np.ones((4,2,3))/np.tile(2*np.ones((4,2))[:,:,np.newaxis],(1,1,3))
(np.ones((4,2,3))/2*np.ones((4,2))[:,:,np.newaxis]).shape

(4, 2, 3)

In [35]:
test_tp = np.ones((N, N, T, Q, Q))



In [36]:
np.einsum("ijtqr,ijt->tqr", test_tp, (dsbmm_dict["A"] > 0)).shape



(5, 4, 4)

In [18]:
test_tp = np.arange(5 * 5 * 3 * 2 * 2).reshape(5, 5, 3, 2, 2)



In [21]:
test_A = np.zeros((5, 5, 3))
test_A[0, 0, 0] = 1
np.einsum("ijtqr,ijt->tqr", test_tp, test_A)



array([[[0., 1.],
        [2., 3.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [31]:
test_degs = np.arange(5 * 3).reshape(5, 3)
test_marg = np.zeros((5, 3, 2))
test_marg[0, :, 0] = 1
tmp = np.einsum("itq,it->tq", test_marg, test_degs)
tmp


array([[0., 0.],
       [1., 0.],
       [2., 0.]])

In [33]:
np.einsum("tq,tr->tqr", tmp, tmp)



array([[[0., 0.],
        [0., 0.]],

       [[1., 0.],
        [0., 0.]],

       [[4., 0.],
        [0., 0.]]])